# Generated by Django 5.2.6 on 2025-10-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ราคา'),
        ),
    ]
