# Generated by Django 5.2.6 on 2025-11-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ประเภทการใช้งาน')),
            ],
            options={
                'verbose_name_plural': 'ประเภทการใช้งาน (Usage)',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_class', models.CharField(blank=True, choices=[('6S', 'รถ6ล้อเล็ก'), ('6M', 'รถ6ล้อกลาง'), ('6_12', 'รถ6-12ล้อใหญ่')], max_length=10, verbose_name='ประเภทขนาดรถ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='core.product', verbose_name='สินค้า')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usage', verbose_name='ประเภทการใช้งาน')),
            ],
            options={
                'verbose_name_plural': 'สเปคสินค้า (Product Spec)',
            },
        ),
    ]
