# Generated by Django 5.2.6 on 2025-11-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productspec_vehicle_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='vehicle_class',
        ),
        migrations.AddField(
            model_name='productspec',
            name='vehicle_classes',
            field=models.JSONField(default=list, verbose_name='ประเภทขนาดรถ'),
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='usage',
        ),
        migrations.AddField(
            model_name='productspec',
            name='usage',
            field=models.ManyToManyField(blank=True, to='core.usage', verbose_name='ประเภทการใช้งาน'),
        ),
    ]
