# Generated by Django 5.2.6 on 2025-11-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_productspec_vehicle_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='vehicle_classes',
        ),
        migrations.AddField(
            model_name='productspec',
            name='vehicle_class',
            field=models.CharField(blank=True, choices=[('4B', 'รถ4ล้อใหญ่'), ('6S', 'รถ6ล้อเล็ก'), ('6M', 'รถ6ล้อกลาง'), ('6B', 'รถ6ล้อใหญ่'), ('10w', 'รถ10ล้อ'), ('12w', 'รถ12ล้อ'), ('TH', 'หัวลาก')], max_length=10, verbose_name='ประเภทขนาดรถ'),
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='usage',
        ),
        migrations.AddField(
            model_name='productspec',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usage', verbose_name='ประเภทการใช้งาน'),
        ),
    ]
