# Generated by Django 5.2.6 on 2025-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_productspec_vehicle_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('4B', 'รถ4ล้อใหญ่'), ('6S', 'รถ6ล้อเล็ก'), ('6M', 'รถ6ล้อกลาง'), ('6B', 'รถ6ล้อใหญ่'), ('10w', 'รถ10ล้อ'), ('12w', 'รถ12ล้อ'), ('TH', 'หัวลาก')], max_length=10, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ชนิดขนาดรถ (VehicleType)',
            },
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='vehicle_class',
        ),
        migrations.AddField(
            model_name='productspec',
            name='usages',
            field=models.ManyToManyField(blank=True, to='core.usage', verbose_name='ประเภทการใช้งาน'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, to='core.vehicletype', verbose_name='ขนาดรถที่รองรับ'),
        ),
    ]
