# Generated by Django 5.2.6 on 2025-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vehicletype_remove_productspec_usage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='vehicle_types',
        ),
        migrations.AddField(
            model_name='productspec',
            name='vehicle_types',
            field=models.JSONField(blank=True, default=list, verbose_name='ขนาดรถที่รองรับ'),
        ),
    ]
