# Generated by Django 5.2.6 on 2025-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_productspec_vehicle_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='vehicle_types',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ขนาดรถที่รองรับ'),
        ),
    ]
