# Generated by Django 5.2.6 on 2025-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_productspec_vehicle_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='vehicle_types',
            field=models.JSONField(blank=True, default=list, verbose_name='ขนาดรถที่รองรับ'),
        ),
    ]
