# Generated by Django 5.2.6 on 2025-11-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_productspec_vehicle_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
