# Generated by Django 5.2.6 on 2025-11-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_vehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ขนาดรถ',
                'verbose_name_plural': 'ขนาดรถ',
            },
        ),
        migrations.AddField(
            model_name='productspec',
            name='vehicle_types_rel',
            field=models.ManyToManyField(blank=True, to='core.vehicletype', verbose_name='ขนาดรถ'),
        ),
    ]
