# Generated by Django 5.2.6 on 2025-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_migrate_vehicle_json_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='vehicle_types',
        ),
        migrations.AlterField(
            model_name='productspec',
            name='vehicle_types_rel',
            field=models.ManyToManyField(blank=True, to='core.vehicletype', verbose_name='ขนาดรถที่รองรับ'),
        ),
    ]
