# Generated by Django 5.2.6 on 2025-11-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_productspec_vehicle_types_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'ขนาดรถ', 'verbose_name_plural': 'ขนาดรถ (Vehicle size )'},
        ),
    ]
