# Generated by Django 5.2.6 on 2025-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_vehicletype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'ขนาดรถ', 'verbose_name_plural': 'ขนาดรถ (Vehicle size )'},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
